root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./build/webserver"
  full_bin = "CGO_ENABLED=1 REMANA_APP_ENV=development REMANA_SERVER_ADDR=:1234 ./build/webserver"
  cmd = "make build"
  delay = 1000
  exclude_dir = ["openapi", "build"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go"]
  include_file = []
  kill_delay = 10
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
