# See https://github.com/ogen-go/ogen/blob/main/examples/_config/example_all.yml.

# sets parser options.
parser:
  # enables type inference for schemas. Schema parser will try to detect schema type by its properties.
  infer_types: true
  #  enables remote references resolving. See https://github.com/ogen-go/ogen/issues/385.
  allow_remote: true
  # is maximum depth of schema generation. Default is 1000.
  depth_limit: 1000

# sets generator options.
generator:
  features:
    enable:
      - "debug/example_tests"
    disable:
      - "ogen/otel"
      - "paths/client"

  # functions to ignore
  ignore_not_implemented: ["discriminator inference"]
