openapi: 3.0.2
info:
  title: Remana Backend
  version: 1.0.0
  description: The backend API for Remana.
  contact:
    email: jj.anggita@gmail.com
  license:
    name: MIT
    url: https://www.mit.edu/~amini/LICENSE.md
servers:
  - url: http://localhost:8080
tags:
  - name: auth
    description: Authentication into the API
  - name: user
    description: User details
  - name: permissions
    description: Access control
  - name: repair_order
    description: Repair order management
  - name: technicians
    description: Technician management
  - name: sales_persons
    description: Sales person management
  - name: damage_types
    description: Damage type management
  - name: phone_conditions
    description: Phone condition management
  - name: phone_equipments
    description: Phone equipment management
  - name: payment_methods
    description: Payment method management
  - name: misc
    description: Miscellaneous endpoints
components:
  securitySchemes:
    sessionCookie:
      $ref: components/securitySchemes/sessionCookie.yaml
security:
  - sessionCookie: []
paths:
  /healthz:
    get:
      $ref: paths/misc/getHealth.yaml
  /auth/login:
    post:
      $ref: paths/auth/login.yaml
  /auth/login-code:
    post:
      $ref: paths/auth/loginCodePrompt.yaml
  /auth/logout:
    post:
      $ref: paths/auth/logout.yaml
  /users/me:
    get:
      $ref: paths/user/getMyUserDetails.yaml
  /repair-orders:
    post:
      $ref: paths/repair_orders/createRepairOrder.yaml
  /technicians:
    post:
      $ref: paths/technicians/createTechnician.yaml
  /sales-persons:
    post:
      $ref: paths/sales_persons/createSalesPerson.yaml
  /damage-types:
    post:
      $ref: paths/damage_types/createDamageType.yaml
  /phone-conditions:
    post:
      $ref: paths/phone_conditions/createPhoneCondition.yaml
  /phone-equipments:
    post:
      $ref: paths/phone_equipments/createPhoneEquipment.yaml
  /payment-methods:
    post:
      $ref: paths/payment_methods/createPaymentMethod.yaml
  /roles:
    post:
      $ref: paths/permissions/createRole.yaml
  /roles/{roleId}/permissions:
    post:
      $ref: paths/permissions/assignPermissionsToRole.yaml
