// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"fmt"
	"net/url"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #
type LoginCodePrompt struct {
	LoginCode string `json:"login_code"`
}

// GetLoginCode returns the value of LoginCode.
func (s *LoginCodePrompt) GetLoginCode() string {
	return s.LoginCode
}

// SetLoginCode sets the value of LoginCode.
func (s *LoginCodePrompt) SetLoginCode(val string) {
	s.LoginCode = val
}

// LoginCodePromptNoContent is response for LoginCodePrompt operation.
type LoginCodePromptNoContent struct{}

// Ref: #
type LoginCodePromptRedirection struct {
	// [URL to POST with login code](#/auth/loginCodePrompt).
	PromptURL url.URL `json:"prompt_url"`
}

// GetPromptURL returns the value of PromptURL.
func (s *LoginCodePromptRedirection) GetPromptURL() url.URL {
	return s.PromptURL
}

// SetPromptURL sets the value of PromptURL.
func (s *LoginCodePromptRedirection) SetPromptURL(val url.URL) {
	s.PromptURL = val
}

func (*LoginCodePromptRedirection) loginRes() {}

// Ref: #
type LoginCredentials struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	StoreCode string `json:"store_code"`
}

// GetUsername returns the value of Username.
func (s *LoginCredentials) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *LoginCredentials) GetPassword() string {
	return s.Password
}

// GetStoreCode returns the value of StoreCode.
func (s *LoginCredentials) GetStoreCode() string {
	return s.StoreCode
}

// SetUsername sets the value of Username.
func (s *LoginCredentials) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *LoginCredentials) SetPassword(val string) {
	s.Password = val
}

// SetStoreCode sets the value of StoreCode.
func (s *LoginCredentials) SetStoreCode(val string) {
	s.StoreCode = val
}

// LoginNoContent is response for Login operation.
type LoginNoContent struct{}

func (*LoginNoContent) loginRes() {}
