// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// AssignPermissionsToRoleParams is parameters of assignPermissionsToRole operation.
type AssignPermissionsToRoleParams struct {
	// ID of the role to assign permissions to.
	RoleId uuid.UUID
}

func unpackAssignPermissionsToRoleParams(packed middleware.Parameters) (params AssignPermissionsToRoleParams) {
	{
		key := middleware.ParameterKey{
			Name: "roleId",
			In:   "path",
		}
		params.RoleId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAssignPermissionsToRoleParams(args [1]string, argsEscaped bool, r *http.Request) (params AssignPermissionsToRoleParams, _ error) {
	// Decode path: roleId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "roleId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.RoleId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "roleId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
