// Code generated by ogen, DO NOT EDIT.

package genapi

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginCodePrompt) SetFake() {
	{
		{
			s.LoginCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginCredentials) SetFake() {
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Password = "string"
		}
	}
	{
		{
			s.StoreCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginResponse) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *LoginResponseType) SetFake() {
	*s = LoginResponseTypeAdmin
}
