// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"net/http"

	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// LoginCodePromptParams is parameters of loginCodePrompt operation.
type LoginCodePromptParams struct {
	// The prompt ID set by [/auth/login](#/auth/login).
	PromptID uuid.UUID
}

func unpackLoginCodePromptParams(packed middleware.Parameters) (params LoginCodePromptParams) {
	{
		key := middleware.ParameterKey{
			Name: "prompt_id",
			In:   "cookie",
		}
		params.PromptID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeLoginCodePromptParams(args [0]string, argsEscaped bool, r *http.Request) (params LoginCodePromptParams, _ error) {
	c := uri.NewCookieDecoder(r)
	// Decode cookie: prompt_id.
	if err := func() error {
		cfg := uri.CookieParameterDecodingConfig{
			Name:    "prompt_id",
			Explode: true,
		}
		if err := c.HasParam(cfg); err == nil {
			if err := c.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.PromptID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "prompt_id",
			In:   "cookie",
			Err:  err,
		}
	}
	return params, nil
}
