// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AssignPermissionsToRole implements assignPermissionsToRole operation.
//
// Assigns permissions to a role.
//
// POST /roles/{roleId}/permissions
func (UnimplementedHandler) AssignPermissionsToRole(ctx context.Context, req *AssignPermissionsToRoleRequest, params AssignPermissionsToRoleParams) error {
	return ht.ErrNotImplemented
}

// CreateDamageType implements createDamageType operation.
//
// Creates a new damage type.
//
// POST /damage-types
func (UnimplementedHandler) CreateDamageType(ctx context.Context, req *CreateDamageTypeRequest) (r *CreateDamageTypeCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePaymentMethod implements createPaymentMethod operation.
//
// Creates a new payment method.
//
// POST /payment-methods
func (UnimplementedHandler) CreatePaymentMethod(ctx context.Context, req *CreatePaymentMethodRequest) (r *CreatePaymentMethodCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePhoneCondition implements createPhoneCondition operation.
//
// Creates a new phone condition.
//
// POST /phone-conditions
func (UnimplementedHandler) CreatePhoneCondition(ctx context.Context, req *CreatePhoneConditionRequest) (r *CreatePhoneConditionCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePhoneEquipment implements createPhoneEquipment operation.
//
// Creates a new phone equipment.
//
// POST /phone-equipments
func (UnimplementedHandler) CreatePhoneEquipment(ctx context.Context, req *CreatePhoneEquipmentRequest) (r *CreatePhoneEquipmentCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRepairOrder implements createRepairOrder operation.
//
// Creates a new repair order.
//
// POST /repair-orders
func (UnimplementedHandler) CreateRepairOrder(ctx context.Context, req *CreateRepairOrderRequest) (r *CreateRepairOrderCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRole implements createRole operation.
//
// Creates a role.
//
// POST /roles
func (UnimplementedHandler) CreateRole(ctx context.Context, req *CreateRoleRequest) (r *CreateRoleCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSalesPerson implements createSalesPerson operation.
//
// Creates a new sales person.
//
// POST /sales-persons
func (UnimplementedHandler) CreateSalesPerson(ctx context.Context, req *CreateSalesPersonRequest) (r *CreateSalesPersonCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTechnician implements createTechnician operation.
//
// Creates a new technician.
//
// POST /technicians
func (UnimplementedHandler) CreateTechnician(ctx context.Context, req *CreateTechnicianRequest) (r *CreateTechnicianCreated, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Returns the health status of the service.
//
// GET /healthz
func (UnimplementedHandler) GetHealth(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetMyUserDetails implements getMyUserDetails operation.
//
// Returns details of the currently logged in user.
//
// GET /users/me
func (UnimplementedHandler) GetMyUserDetails(ctx context.Context) (r *UserDetails, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Logs in with credentials.
//
// POST /auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginCredentials) (r *LoginResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// LoginCodePrompt implements loginCodePrompt operation.
//
// Logs store employees in with the login code given by the store admin. Should only be called after
// [/auth/login](#/auth/login) has been called.
//
// POST /auth/login-code
func (UnimplementedHandler) LoginCodePrompt(ctx context.Context, req *LoginCodePrompt) error {
	return ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Logs out current session.
//
// POST /auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
