// Code generated by ogen, DO NOT EDIT.

package genapi

import (
	"net/url"
)

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.Code = int32(0)
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginCodePrompt) SetFake() {
	{
		{
			s.LoginCode = "string"
		}
	}
}

// SetFake set fake values.
func (s *LoginCodePromptRedirection) SetFake() {
	{
		{
			s.PromptURL = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
		}
	}
}

// SetFake set fake values.
func (s *LoginCredentials) SetFake() {
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.Password = "string"
		}
	}
	{
		{
			s.StoreCode = "string"
		}
	}
}
