// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package gensql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Store struct {
	StoreID      pgtype.UUID
	StoreName    string
	StoreCode    string
	StoreAddress string
	PhoneNumber  string
}
