// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStoreByID = `-- name: GetStoreByID :one
SELECT store_id, store_name, store_code, store_address, phone_number FROM stores
WHERE store_id = $1 LIMIT 1
`

func (q *Queries) GetStoreByID(ctx context.Context, storeID pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, storeID)
	var i Store
	err := row.Scan(
		&i.StoreID,
		&i.StoreName,
		&i.StoreCode,
		&i.StoreAddress,
		&i.PhoneNumber,
	)
	return i, err
}
