name: Upload Go test results
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test -json -count=1 -tags unit,integration,e2e ./... > test-results.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
